spring:
  application:
    name:
      order-service

  datasource:
    url:
        jdbc:postgresql://localhost:5432/ecommerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#      bindings:
#        output:
#          destination: order-topic
#        input:
#          destination: order-topic
