spring:
  application:
    name:
      order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/device_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    function:
      definition: producer;consumer
    stream:
      kafka:
        binder:
          brokers: 'broker:29092'
      bindings:
        producer-out-0:
          destination: first-topic
        consumer-in-0:
          destination: first-topic