spring:
  application:
    name:
      order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/device_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    stream:
      bindings:
        order-out-0:
          destination: orders

  kafka:
    bootstrap-servers: "kafka:9092"