spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: none
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
        naming :
          physical-strategy: com.ecommerce.productservice.config.CamelCaseToUppercaseTablesNamingStrategy



  application:
    name: product-service


    cloud:
      #    function:
      #      definition: producer;consumer
      stream:
        kafka:
          binder:
            brokers: 'broker:29092'
        bindings:
          orderPlaced-out-0:
            destination: order-placed-topic
            contentType: application/json
          orderPlaced-in-0:
            destination: order-placed-topic
            contentType: application/json


server:
  port: 8088

