server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

info:
  app:
    name: Gateway Service
    description: Gateway Service
    version: 1.0.0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    region: default
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: info,health,shutdown,routes,gateway,circuitBreakers,circuitbreakerevents

  endpoint:
    shutdown:
      enabled: true
    gateway:
      enabled: true
    circuitBreakers:
      enabled: true

  info:
    env:
      enabled: true


  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
